### ISSUE TITLE
仿造 GitHub 的版型是怎麼做的

### ISSUE THREAD

**Issue by dwy6626** [jie255057/jie255057.github.io#1]
不好意思打擾了  
在網路上找到，覺得仿造 GitHub 的版型很有趣，好奇這是用什麼做的  
謝謝

**Comment by jie255057** [comment]
你好啊，那是hexo 的版型 你可以去看看別人做的 很多，好奇問一下，怎麼會逛到我的blog😂

De-Wei Ye <notifications@github.com>於 2020年7月24日 週五，上午11:19寫道：

**Comment by dwy6626** [comment]
我在查 rails 的 STI 找到的～  
原來是 Hexo 的 theme  
謝謝你的回答  
你可以把 issue 關掉了XD
